/**
 * export-docs.ts
 *
 * Serialises a completed JobState into two agent-ready markdown hand-off documents:
 *
 *   1. {BrandName}_BRANDING.md  — Brand identity, design tokens, persona selections
 *   2. {BrandName}_CONTENT.md   — Full site structure with AEO-optimised content per section
 *
 * These files are included in the download ZIP so a downstream design or
 * content agent has everything it needs to recreate or extend the site.
 */

import { JobState } from './types';

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Derive a clean brand name slug for use in filenames. */
export function brandSlug(job: JobState): string {
  const name =
    job.brandDna?.brandName ||
    job.phases.analyze.entityMap?.businessName ||
    'brand';
  return name
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

const OBJECTIVE_LABELS: Record<string, string> = {
  'sell-products':  'Sell Products (e-commerce / shop)',
  'make-bookings':  'Make Bookings (appointments / schedule)',
  'capture-leads':  'Capture Leads (enquiry / quote / consult)',
  'other':          'General / Informational',
};

const PERSONA_LABELS: Record<string, Record<string, string>> = {
  layout:       { spacious: 'Spacious & Airy (Apple style)', dense: 'Information Dense (Bloomberg style)' },
  tone:         { professional: 'The Professional (authoritative, measured)', disruptor: 'The Disruptor (punchy, provocative)' },
  imagery:      { 'human-centric': 'Human-Centric (photography, faces, warmth)', 'abstract-tech': 'Abstract / Tech (geometric, data-precise)' },
  motion:       { static: 'Static & Grounded (deliberate, calm)', 'high-motion': 'High Motion / Parallax (alive, dynamic)' },
  architecture: { 'linear-story': 'Linear Story (single scrollable narrative)', 'deep-hub': 'Deep Hub (multi-page, content-rich)' },
};

function personaLabel(key: string, value: string): string {
  return PERSONA_LABELS[key]?.[value] ?? value;
}

// ── Document 1: BRANDING ──────────────────────────────────────────────────────

/**
 * Generates {BrandName}_BRANDING.md
 *
 * Covers:
 *  - Business identity (name, category, description, value proposition)
 *  - 60-30-10 colour palette with hex values
 *  - Typography (heading + body fonts, scale)
 *  - Spacing & layout tokens
 *  - Vibe Forge persona selections (all 5 duels)
 *  - Site objective & fidelity mode
 *  - AEO performance baseline (original site score)
 *  - Real extracted content signals (staff, trust signals)
 */
export function generateBrandingDoc(job: JobState): string {
  const entity = job.phases.analyze.entityMap;
  const dna = job.brandDna;
  const tokens = job.phases.analyze.tokens;
  const persona = job.sitePersona;
  const rc = job.realSiteContent;
  const screenshotUrl = job.phases.extract.screenshotUrl;

  const brandName = dna?.brandName || entity?.businessName || 'Unknown Brand';
  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# ${brandName} — Brand Identity Brief`);
  lines.push('');
  lines.push('> Generated by **ALIAS COMPILER** — AEO-First Rebuild Engine');
  lines.push(`> Source URL: ${job.url}`);
  lines.push(`> Generated: ${new Date().toISOString()}`);
  if (screenshotUrl) {
    lines.push(`> Original Site Screenshot: ${screenshotUrl}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Business Identity ────────────────────────────────────────────────────────
  lines.push('## 1. Business Identity');
  lines.push('');
  if (entity) {
    lines.push(`| Field | Value |`);
    lines.push(`|---|---|`);
    lines.push(`| **Brand Name** | ${brandName} |`);
    lines.push(`| **Category** | ${entity.businessCategory || '—'} |`);
    lines.push(`| **Type** | ${entity.businessType || entity.industry || '—'} |`);
    lines.push(`| **Primary Service** | ${entity.primaryService || '—'} |`);
    lines.push(`| **Target Audience** | ${entity.targetAudience || '—'} |`);
    lines.push('');
    if (entity.valueProposition) {
      lines.push('### Value Proposition');
      lines.push('');
      lines.push(`> ${entity.valueProposition}`);
      lines.push('');
    }
    if (entity.entities?.length) {
      lines.push('### Key Topic Entities');
      lines.push('');
      lines.push(entity.entities.map(e => `- ${e}`).join('\n'));
      lines.push('');
    }
  }

  // ── Brand Voice ──────────────────────────────────────────────────────────────
  if (dna?.voiceTone) {
    lines.push('### Voice & Tone');
    lines.push('');
    lines.push(`> ${dna.voiceTone}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ── Colour Palette ───────────────────────────────────────────────────────────
  lines.push('## 2. Colour Palette (60-30-10 System)');
  lines.push('');
  lines.push('> The 60-30-10 rule: 60% dominant (backgrounds), 30% supporting (structure), 10% accent (CTAs/highlights)');
  lines.push('');

  if (dna) {
    lines.push('| Role | Hex | Usage |');
    lines.push('|---|---|---|');
    lines.push(`| **Dominant (60%)** | \`${dna.palette.dominant}\` | Primary background / large surface areas |`);
    lines.push(`| **Supporting (30%)** | \`${dna.palette.supporting}\` | Nav bar, cards, secondary sections |`);
    lines.push(`| **Accent (10%)** | \`${dna.palette.accent}\` | CTAs, highlights, interactive elements |`);
    lines.push(`| **Text** | \`${dna.palette.text}\` | Primary body copy colour |`);
    lines.push(`| **Text Muted** | \`${dna.palette.textMuted}\` | Secondary text, captions, placeholders |`);
  } else if (tokens) {
    lines.push('| Role | Hex |');
    lines.push('|---|---|');
    lines.push(`| **Primary** | \`${tokens.colors.primary}\` |`);
    lines.push(`| **Secondary** | \`${tokens.colors.secondary}\` |`);
    lines.push(`| **Surface** | \`${tokens.colors.surface}\` |`);
    lines.push(`| **Text** | \`${tokens.colors.text}\` |`);
    lines.push(`| **Accent** | \`${tokens.colors.accent}\` |`);
    if (tokens.colors.border) lines.push(`| **Border** | \`${tokens.colors.border}\` |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Typography ───────────────────────────────────────────────────────────────
  lines.push('## 3. Typography');
  lines.push('');

  const headingFont = dna?.typePairing.heading || tokens?.typography.headingFont;
  const bodyFont    = dna?.typePairing.body    || tokens?.typography.bodyFont;

  if (headingFont || bodyFont || tokens?.typography) {
    lines.push('| Property | Value |');
    lines.push('|---|---|');
    if (headingFont) lines.push(`| **Heading Font** | ${headingFont} |`);
    if (bodyFont)    lines.push(`| **Body Font** | ${bodyFont} |`);
    if (tokens?.typography.baseSizePx)  lines.push(`| **Base Size** | ${tokens.typography.baseSizePx}px |`);
    if (tokens?.typography.scaleRatio)  lines.push(`| **Scale Ratio** | ${tokens.typography.scaleRatio} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Layout & Spacing Tokens ───────────────────────────────────────────────────
  if (tokens) {
    lines.push('## 4. Layout & Spacing');
    lines.push('');
    lines.push('| Property | Value |');
    lines.push('|---|---|');
    lines.push(`| **Container Width** | ${tokens.spacing.containerWidthPx}px |`);
    lines.push(`| **Section Padding** | ${tokens.spacing.sectionPaddingPx}px |`);
    lines.push(`| **Column Gap** | ${tokens.spacing.columnGapPx}px |`);
    lines.push(`| **Nav Type** | ${tokens.layout.navType} |`);
    lines.push(`| **Nav Style** | ${tokens.layout.navStyle} |`);
    lines.push(`| **Hero Type** | ${tokens.layout.heroType} |`);
    lines.push(`| **Column Count** | ${tokens.layout.columnCount} |`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // ── Vibe Forge Persona ───────────────────────────────────────────────────────
  lines.push('## 5. Design Persona (Vibe Forge Selections)');
  lines.push('');
  lines.push('These selections drive content volume, visual style, copy tone, motion, and site architecture.');
  lines.push('');

  if (persona) {
    lines.push('| Dimension | Selection |');
    lines.push('|---|---|');
    lines.push(`| **Duel 1 — Layout** | ${personaLabel('layout', persona.layout)} |`);
    lines.push(`| **Duel 2 — Tone** | ${personaLabel('tone', persona.tone)} |`);
    lines.push(`| **Duel 3 — Imagery** | ${personaLabel('imagery', persona.imagery)} |`);
    lines.push(`| **Duel 4 — Motion** | ${personaLabel('motion', persona.motion)} |`);
    lines.push(`| **Duel 5 — Architecture** | ${personaLabel('architecture', persona.architecture)} |`);
    lines.push('');

    // Content volume implication
    const isDense = persona.layout === 'dense';
    lines.push('### Content Volume Implication');
    lines.push('');
    lines.push(isDense
      ? '**Information Dense** — body copy per section: 100–200 words. Rich detail, 5–8 bullet items per list, 4–6 FAQ pairs with substantive 2–3 sentence answers.'
      : '**Spacious & Airy** — body copy per section: 30–60 words maximum. Headings carry the weight. 3–5 short bullet items. 3–4 FAQ pairs with 1-sentence answers.');
    lines.push('');
  } else {
    lines.push('_Persona not captured (job was run without Vibe Forge)._');
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // ── Site Configuration ───────────────────────────────────────────────────────
  lines.push('## 6. Site Configuration');
  lines.push('');
  lines.push('| Setting | Value |');
  lines.push('|---|---|');
  lines.push(`| **Site Objective** | ${OBJECTIVE_LABELS[job.siteObjective] ?? job.siteObjective} |`);
  lines.push(`| **Fidelity Mode** | ${job.fidelityMode === 'aeo-first' ? 'AEO-First (rewrites structure for AI)' : 'Brand-First (keeps original layout + fonts)'} |`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── AEO Baseline ────────────────────────────────────────────────────────────
  if (job.originalScore) {
    const os = job.originalScore;
    const rebuilt = job.phases.audit.score;
    lines.push('## 7. AEO Performance Baseline');
    lines.push('');
    lines.push('| Category | Original Site | Rebuilt Site |');
    lines.push('|---|---|---|');
    lines.push(`| **Overall** | ${os.overall}/100 | ${rebuilt?.overall ?? '—'}/100 |`);
    lines.push(`| Content Structure | ${os.content_structure}/100 | ${rebuilt?.content_structure ?? '—'}/100 |`);
    lines.push(`| E-E-A-T | ${os.eeat}/100 | ${rebuilt?.eeat ?? '—'}/100 |`);
    lines.push(`| Technical | ${os.technical}/100 | ${rebuilt?.technical ?? '—'}/100 |`);
    lines.push(`| Entity Alignment | ${os.entity_alignment}/100 | ${rebuilt?.entity_alignment ?? '—'}/100 |`);
    if (rebuilt) {
      const delta = rebuilt.overall - os.overall;
      lines.push('');
      lines.push(`> **AEO Improvement: ${delta >= 0 ? '+' : ''}${delta} points** (${os.overall} → ${rebuilt.overall})`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // ── Real Extracted Content Signals ──────────────────────────────────────────
  if (rc) {
    lines.push('## 8. Extracted Content Signals');
    lines.push('');
    lines.push('_Real content found in the original site — use these verbatim or as close rewrites._');
    lines.push('');

    if (rc.staffMembers.length) {
      lines.push('### Team & Credentials');
      lines.push('');
      rc.staffMembers.forEach(s => lines.push(`- ${s}`));
      lines.push('');
    }
    if (rc.trustSignals.length) {
      lines.push('### Trust Signals & Certifications');
      lines.push('');
      rc.trustSignals.forEach(t => lines.push(`- ${t}`));
      lines.push('');
    }
    if (rc.stats.length) {
      lines.push('### Stats & Proof Points');
      lines.push('');
      rc.stats.forEach(s => lines.push(`- ${s}`));
      lines.push('');
    }
    if (rc.locations.length) {
      lines.push('### Locations / Audience Targeting');
      lines.push('');
      rc.locations.forEach(l => lines.push(`- ${l}`));
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ── Document 2: CONTENT ───────────────────────────────────────────────────────

/**
 * Generates {BrandName}_CONTENT.md
 *
 * Covers:
 *  - AEO strategy rationale and focus areas
 *  - Full site structure (pages, section blueprints, importance levels)
 *  - Per-section content: heading, body, list items
 *  - JSON-LD schemas per page
 *  - Internal link suggestions
 *  - Real testimonials extracted from the original site
 */
export function generateContentDoc(job: JobState): string {
  const entity = job.phases.analyze.entityMap;
  const rc = job.realSiteContent;
  const brandName = job.brandDna?.brandName || entity?.businessName || 'Unknown Brand';
  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# ${brandName} — AEO Content Brief`);
  lines.push('');
  lines.push('> Generated by **ALIAS COMPILER** — AEO-First Rebuild Engine');
  lines.push(`> Source URL: ${job.url}`);
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('This document contains the full AEO-optimised content plan for the rebuilt site.');
  lines.push('All content has been structured for maximum extractability by AI answer engines');
  lines.push('(ChatGPT, Perplexity, Google AI Overviews, etc.).');
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── AEO Strategy ────────────────────────────────────────────────────────────
  const strategy = job.aeoStrategy;
  if (strategy) {
    lines.push('## AEO Strategy');
    lines.push('');
    if (strategy.rationale) {
      lines.push(`> ${strategy.rationale}`);
      lines.push('');
    }
    if (strategy.focusAreas.length) {
      lines.push('### Priority Focus Areas');
      lines.push('');
      strategy.focusAreas.forEach(f => lines.push(`- **${f}**`));
      lines.push('');
    }
    if (strategy.contentGuidance.length) {
      lines.push('### Content Guidance');
      lines.push('');
      strategy.contentGuidance.forEach(g => lines.push(`- ${g}`));
      lines.push('');
    }
    // Section priorities
    const critical  = Object.entries(strategy.sectionPriorities).filter(([, v]) => v === 'critical').map(([k]) => k);
    const important = Object.entries(strategy.sectionPriorities).filter(([, v]) => v === 'important').map(([k]) => k);
    if (critical.length || important.length) {
      lines.push('### Section Priorities');
      lines.push('');
      if (critical.length)  lines.push(`- **Critical:** ${critical.join(', ')}`);
      if (important.length) lines.push(`- **Important:** ${important.join(', ')}`);
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  // ── Page-by-page content ─────────────────────────────────────────────────────
  lines.push('## Site Content');
  lines.push('');

  const pages = Object.values(job.pages).filter(p => p.status === 'done' && p.aeoContent);
  // Home first, then alphabetically
  const sorted = [
    ...pages.filter(p => p.slug === 'home'),
    ...pages.filter(p => p.slug !== 'home').sort((a, b) => a.title.localeCompare(b.title)),
  ];

  sorted.forEach((page, pageIdx) => {
    const content = page.aeoContent!;
    const planPage = job.sitePlan?.pages.find(p => p.slug === page.slug);

    lines.push(`### Page ${pageIdx + 1}: ${page.title}`);
    lines.push('');
    lines.push(`| Field | Value |`);
    lines.push(`|---|---|`);
    lines.push(`| **Slug** | \`${page.slug}\` |`);
    lines.push(`| **URL** | ${page.url} |`);
    lines.push(`| **Page Title** | ${content.title} |`);
    if (planPage?.intent) {
      lines.push(`| **Page Intent** | ${planPage.intent} |`);
    }
    lines.push('');

    lines.push('#### Meta');
    lines.push('');
    lines.push(`- **H1:** ${content.h1}`);
    lines.push(`- **Meta Description:** ${content.metaDescription}`);
    lines.push('');

    // Section blueprint from plan (importance levels)
    const importanceMap: Record<string, string> = {};
    planPage?.sections.forEach(s => { importanceMap[s.type] = s.importance; });

    // Sections
    lines.push('#### Sections');
    lines.push('');

    content.sections.forEach((section, sIdx) => {
      const importance = importanceMap[section.type];
      const importanceBadge = importance === 'critical' ? ' 🔴 CRITICAL' : importance === 'important' ? ' 🟡 IMPORTANT' : '';
      lines.push(`**${sIdx + 1}. ${section.heading}** *(${section.type}${importanceBadge})*`);
      lines.push('');
      if (section.body) {
        lines.push(section.body);
        lines.push('');
      }
      if (section.isList && section.listItems?.length) {
        section.listItems.forEach(item => lines.push(`- ${item}`));
        lines.push('');
      }
    });

    // Internal link suggestions
    if (content.internalLinkSuggestions.length) {
      lines.push('#### Internal Link Suggestions');
      lines.push('');
      content.internalLinkSuggestions.forEach(l => lines.push(`- ${l}`));
      lines.push('');
    }

    // JSON-LD schemas
    if (content.jsonLd.length) {
      lines.push('#### Structured Data (Schema.org)');
      lines.push('');
      lines.push('```json');
      lines.push(JSON.stringify(content.jsonLd, null, 2));
      lines.push('```');
      lines.push('');
    }

    if (pageIdx < sorted.length - 1) {
      lines.push('---');
      lines.push('');
    }
  });

  // ── Testimonials ─────────────────────────────────────────────────────────────
  if (rc?.testimonials.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Client Testimonials (Extracted from Original Site)');
    lines.push('');
    lines.push('_Use these verbatim or as close rewrites — they are real attributed quotes._');
    lines.push('');
    rc.testimonials.forEach((t, i) => {
      lines.push(`### Testimonial ${i + 1}`);
      lines.push('');
      lines.push(`> ${t}`);
      lines.push('');
    });
  }

  // ── Services ─────────────────────────────────────────────────────────────────
  if (rc?.services.length) {
    lines.push('---');
    lines.push('');
    lines.push('## Services (Extracted from Original Site)');
    lines.push('');
    rc.services.forEach(s => lines.push(`- ${s}`));
    lines.push('');
  }

  return lines.join('\n');
}
