import { NextRequest } from 'next/server';
import { getJob } from '@/lib/job-store';
import JSZip from 'jszip';

type RouteContext = { params: Promise<{ jobId: string }> };

export async function GET(_req: NextRequest, ctx: RouteContext) {
  const { jobId } = await ctx.params;
  const job = getJob(jobId);

  if (!job) {
    return new Response('Job not found', { status: 404 });
  }

  const html = job.phases.synthesize.builtHtml;
  const score = job.phases.audit.score;
  const tokens = job.phases.analyze.tokens;
  const aeoContent = job.phases.draft.aeoContent;

  if (!html) {
    return new Response('Build not complete', { status: 202 });
  }

  const zip = new JSZip();

  // Main HTML file
  zip.file('index.html', html);

  // AEO report
  if (score) {
    const report = `# AEO Audit Report
Generated by ALIAS COMPILER
Source URL: ${job.url}

## Overall Score: ${score.overall}/100

| Category | Score |
|---|---|
| Content Structure | ${score.content_structure}/100 |
| E-E-A-T | ${score.eeat}/100 |
| Technical | ${score.technical}/100 |
| Entity Alignment | ${score.entity_alignment}/100 |

## AI Summary
> ${score.aiSummary}

## AI Readability
Can summarize in 2 sentences: ${score.canSummarizeIn2Sentences ? '✓ YES' : '✗ NO'}

## Recommendations
${score.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}
`;
    zip.file('AEO_REPORT.md', report);
  }

  // Design tokens
  if (tokens) {
    zip.file('design-tokens.json', JSON.stringify(tokens, null, 2));
  }

  // Schema.org blocks
  if (aeoContent?.jsonLd?.length) {
    zip.file('schema.json', JSON.stringify(aeoContent.jsonLd, null, 2));
  }

  // README
  zip.file('README.md', `# ${job.phases.analyze.entityMap?.businessName || 'Site'} — Rebuilt by ALIAS COMPILER

## Source
${job.url}

## AEO Score: ${score?.overall ?? 'N/A'}/100

## Files
- \`index.html\` — AEO-optimised rebuilt website
- \`AEO_REPORT.md\` — Full audit report with recommendations
- \`design-tokens.json\` — Extracted design tokens (colors, fonts, spacing)
- \`schema.json\` — Schema.org JSON-LD structured data blocks

## Next Steps
1. Review AEO_REPORT.md recommendations
2. Add real images (replace placeholder references)
3. Connect to your CMS or deploy directly to Vercel
4. Monitor AI citations on Perplexity, ChatGPT, and Google AI Overviews
`);

  const buffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' });

  const domain = new URL(job.url).hostname.replace(/\./g, '-');
  return new Response(buffer, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="alias-rebuild-${domain}.zip"`,
    },
  });
}
