import { NextRequest } from 'next/server';
import { getJob } from '@/lib/job-store';
import { generateBrandingDoc, generateContentDoc, brandSlug } from '@/lib/export-docs';
import JSZip from 'jszip';

type RouteContext = { params: Promise<{ jobId: string }> };

export async function GET(_req: NextRequest, ctx: RouteContext) {
  const { jobId } = await ctx.params;
  const job = getJob(jobId);

  if (!job) {
    return new Response('Job not found', { status: 404 });
  }

  const homeHtml  = job.phases.synthesize.builtHtml;
  const score     = job.phases.audit.score;
  const tokens    = job.phases.analyze.tokens;
  const aeoContent = job.phases.draft.aeoContent;

  if (!homeHtml) {
    return new Response('Build not complete', { status: 202 });
  }

  const zip = new JSZip();
  const slug = brandSlug(job);

  // ── HTML pages ──────────────────────────────────────────────────────────────
  // Homepage
  zip.file('pages/index.html', homeHtml);

  // Sub-pages — include every done page
  const donePages = Object.values(job.pages).filter(p => p.status === 'done' && p.html);
  for (const page of donePages) {
    if (page.slug === 'home') continue; // already saved as index.html
    zip.file(`pages/${page.slug}.html`, page.html);
  }

  // ── Agent hand-off documents ────────────────────────────────────────────────
  try {
    zip.file(`${slug}_BRANDING.md`, generateBrandingDoc(job));
  } catch (err) {
    console.error('[download] branding doc generation failed:', err);
  }

  try {
    zip.file(`${slug}_CONTENT.md`, generateContentDoc(job));
  } catch (err) {
    console.error('[download] content doc generation failed:', err);
  }

  // ── AEO audit report ────────────────────────────────────────────────────────
  if (score) {
    const originalScore = job.originalScore;
    const delta = originalScore ? score.overall - originalScore.overall : null;

    const report = `# AEO Audit Report
Generated by ALIAS COMPILER
Source URL: ${job.url}

## Overall Score: ${score.overall}/100${delta !== null ? ` (+${delta} vs original)` : ''}

| Category | Rebuilt Site | Original Site |
|---|---|---|
| Content Structure | ${score.content_structure}/100 | ${originalScore?.content_structure ?? '—'}/100 |
| E-E-A-T | ${score.eeat}/100 | ${originalScore?.eeat ?? '—'}/100 |
| Technical | ${score.technical}/100 | ${originalScore?.technical ?? '—'}/100 |
| Entity Alignment | ${score.entity_alignment}/100 | ${originalScore?.entity_alignment ?? '—'}/100 |

## AI Summary
> ${score.aiSummary}

## AI Readability
Can summarize in 2 sentences: ${score.canSummarizeIn2Sentences ? '✓ YES' : '✗ NO'}

## Recommendations
${score.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}
`;
    zip.file('AEO_REPORT.md', report);
  }

  // ── Design tokens (machine-readable) ────────────────────────────────────────
  if (tokens) {
    zip.file('design-tokens.json', JSON.stringify(tokens, null, 2));
  }

  // ── Schema.org blocks (all pages) ───────────────────────────────────────────
  const allSchemas: object[] = [];
  if (aeoContent?.jsonLd?.length) allSchemas.push(...aeoContent.jsonLd);
  for (const page of donePages) {
    if (page.slug !== 'home' && page.aeoContent?.jsonLd?.length) {
      allSchemas.push(...page.aeoContent.jsonLd);
    }
  }
  if (allSchemas.length) {
    zip.file('schema.json', JSON.stringify(allSchemas, null, 2));
  }

  // ── README ───────────────────────────────────────────────────────────────────
  const brandName = job.brandDna?.brandName || job.phases.analyze.entityMap?.businessName || 'Site';
  const allPageFiles = ['pages/index.html', ...donePages.filter(p => p.slug !== 'home').map(p => `pages/${p.slug}.html`)];

  zip.file('README.md', `# ${brandName} — Rebuilt by ALIAS COMPILER

## Source
${job.url}

## AEO Score: ${score?.overall ?? 'N/A'}/100${job.originalScore ? ` (original: ${job.originalScore.overall}/100)` : ''}

## Files

### Agent Hand-off Documents
- \`${slug}_BRANDING.md\` — Brand identity, colour palette, typography, persona, and design tokens
- \`${slug}_CONTENT.md\` — Full site structure with AEO-optimised content for every page and section

### HTML Pages (${allPageFiles.length})
${allPageFiles.map(f => `- \`${f}\``).join('\n')}

### Supporting Files
- \`AEO_REPORT.md\` — Full audit report with score breakdown and recommendations
- \`design-tokens.json\` — Extracted design tokens (colors, fonts, spacing) as JSON
- \`schema.json\` — Schema.org JSON-LD structured data blocks (all pages)

## Next Steps
1. Pass \`${slug}_BRANDING.md\` and \`${slug}_CONTENT.md\` to your design/content agent
2. Review \`AEO_REPORT.md\` for improvement recommendations
3. Add real images (replace placeholder references in HTML)
4. Connect to your CMS or deploy directly to Vercel
5. Monitor AI citations on Perplexity, ChatGPT, and Google AI Overviews
`);

  const buffer = await zip.generateAsync({ type: 'arraybuffer', compression: 'DEFLATE' });

  const domain = new URL(job.url).hostname.replace(/\./g, '-');
  return new Response(buffer, {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="alias-rebuild-${domain}.zip"`,
    },
  });
}
